version: '3.9'

services:
  keycloak:
    image: quay.io/keycloak/keycloak:24.0.1
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    command: start-dev --import-realm
    ports:
      - "8080:8080"
    volumes:
      - ./keycloak:/opt/keycloak/data/import
    healthcheck:
      test: curl --fail http://localhost:8080/ || exit 1
      interval: 10s
      retries: 10

  flask-app:
    build:
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    environment:
      - FLASK_ENV=development
      - KEYCLOAK_SERVER_URL=http://keycloak:8080
      - KEYCLOAK_REALM=demo-realm
      - KEYCLOAK_CLIENT_ID=flask-client
      - KEYCLOAK_CLIENT_SECRET=YOUR_CLIENT_SECRET
    command: ["python", "main.py"]
    env_file:
      - .env
    depends_on:
      keycloak:
        condition: service_healthy
