services:
  web:
    build: .
    image: mywebapp
    ports:
      - "15000:5000"
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - frontend
  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - backend
networks:
  frontend:
  backend:
