services:
  web:
    build: .
    image: mywebapp
    ports:
      - "127.0.0.1:5000:5000"
    read_only: true
    mem_limit: 100m
    pids_limit: 100
    security_opt:
      - no-new-privileges:true
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 --port=5000
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    depends_on:
      - db
    networks:
      - frontend
  db:
    image: postgres:13
    env_file:
      - .env
    networks:
      - backend
networks:
  frontend:
  backend:
