services:
  juice:
    image: bkimminich/juice-shop
    restart: unless-stopped
    ports:
      - "3000:3000"           # baseline /-‐ BEFORE the WAF
    networks:
      - public

  zap:
    image: zaproxy/zap-stable
    user: zap
    command: ["zap-webswing.sh"]   # desktop-style UI in a browser
    ports:
      - "8080:8080"          # http://<host>:8080/zap
    networks:
      - public

networks:
  public:
